default: &default
  github_organization: 'icalialabs'

development:
  <<: *default
  secret_key_base: c76413efef3f5fb9f5c3e084152447b3dee9a019f1f6ae264cd634f622ad7984d8d852de36860336347b1f428703fbb4a569278c0f91dcf52ac350a43455a342
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>
