development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["github_access_token"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["github_access_token"] %>
