default: &default
  github_organization: 'IcaliaLabs'

development:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>

test:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>
